source = ~/.cache/wal/colors-hyprland.conf

general {
  ignore_empty_input = true
}

animations {
  animation = fadeIn, on, 2, default
  animation = fadeOut, on, 2, default
}

background {
  monitor =
  path = ~/.cache/wal/image
  color = rgba(0,0,0,0)
  blur_passes = 4
  blur_size = 4
}

label {
  shadow_passes = 2
  shadow_color = $background

  monitor =
  text = cmd[update:1000] date -Iseconds
  text_align = center
  color = $foreground
  font_size = 32
  font_family = Iosevka
  position = 0, 32
}

label {
  shadow_passes = 2
  shadow_color = $background

  monitor =
  text = cmd[] shuf -n 1 ~/.scripts/hypr/motd
  text_align = center
  color = $foreground
  font_size = 16
  font_family = Iosevka
  position = 0, -16
}

input-field {
  monitor =
  size = 300, 60
  outline_thickness = 2
  outer_color = $color1
  inner_color = $background
  font_color = $foreground
  font_family = Iosevka
  fade_on_empty = true
  fade_timeout = 1000
  placeholder_text = 
  rounding = 8
  fail_color = rgb(255,0,0)
  fail_text = 
  position = 0, 32
  valign = bottom
}
