colorscheme vimper
source /usr/share/nvim/archlinux.lua
set number
set notermguicolors
set tabstop=2
set shiftwidth=2
set modelines=0
set guicursor=a:blinkon100
set linebreak
set bri
set clipboard+=unnamedplus
set cul
set culopt=number
